### ISSUE TITLE
小米note测试，权限拒绝后不能再次选择

### ISSUE THREAD

**Issue by lrnrzg** [alidili/PermissionDemo#1]
点了拒绝授权以后，不会再次弹出dialog，而是显示''相机权限已被禁止''的Toast,并且shouldShowRequestPermissionRationale（）一直返回false。

**Comment by alidili** [comment]
MIUI的权限申请流程基本与Google一致，只不过省去了“不再询问”选项，一次拒绝后下次不会再弹出权限弹框，相当于第一次拒绝默认就选中了“不再询问”选项。

**Comment by alidili** [comment]
MIUI的权限申请流程基本与Google一致，只不过省去了“不再询问”选项，一次拒绝后下次不会再弹出权限弹框，相当于第一次拒绝默认就选中了“不再询问”选项。 @MarshallZhug

**Comment by lrnrzg** [comment]
那就不能实现拒绝后再次进行选择么？

**Comment by alidili** [comment]
拒绝之后只能去小米的安全中心手动开启了，在6.0出现之前MIUI就已经有类似的动态权限管理了，现在使用的这套权限管理是和Google结合之后的。 @MarshallZhug

**Comment by lrnrzg** [comment]
@alidili  明白了 thx
